# Generated by Django 6.0.5 on 2026-05-18 14:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('child_id', models.UUIDField(db_index=True, help_text='References Child in profile_service')),
                ('parent_id', models.UUIDField(db_index=True, help_text='References CustomUser in auth_service — set from JWT')),
                ('date_recorded', models.DateField()),
                ('age_at_recording_months', models.PositiveSmallIntegerField(blank=True, help_text='Age in months at time of measurement (optional, can be calculated client-side)', null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bmi', models.DecimalField(blank=True, decimal_places=2, help_text='Auto-calculated from weight and height. Do not set manually.', max_digits=5, null=True)),
                ('head_circumference_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('foot_size_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ear_size_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('neck_circumference_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('wrist_circumference_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('manual', 'Saisie manuelle'), ('ocr_import', 'Import OCR'), ('doctor_entry', 'Saisie médecin (futur)'), ('imported', 'Importé')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'measurements',
                'ordering': ['-date_recorded', '-created_at'],
            },
        ),
    ]
