# Generated by Django 5.2.14 on 2026-05-25 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='ocr_import_id',
            field=models.UUIDField(blank=True, help_text='References OCRImport in ocr_service for idempotency', null=True, unique=True),
        ),
    ]
