# Generated by Django 6.0.5 on 2026-05-20 11:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OCRImport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parent_id', models.UUIDField(db_index=True, help_text='Set from JWT — never from request body')),
                ('child_id', models.UUIDField(blank=True, db_index=True, help_text='Optional: references Child in profile_service', null=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='ocr_imports/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échoué')], default='pending', max_length=20)),
                ('raw_text', models.TextField(blank=True)),
                ('extracted_data', models.JSONField(default=dict, help_text='Candidate measurement values parsed from OCR text. Must be verified by parent.')),
                ('warnings', models.JSONField(default=list, help_text='List of warning messages about extraction quality.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ocr_imports',
                'ordering': ['-created_at'],
            },
        ),
    ]
