# Generated by Django 5.2.14 on 2026-05-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrimport',
            name='confirmation_status',
            field=models.CharField(choices=[('pending_review', 'En attente de révision'), ('confirmed', 'Confirmé'), ('discarded', 'Rejeté')], default='pending_review', max_length=20),
        ),
        migrations.AddField(
            model_name='ocrimport',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ocrimport',
            name='confirmed_data',
            field=models.JSONField(blank=True, default=dict, help_text='Final values chosen or typed by the parent.'),
        ),
        migrations.AddField(
            model_name='ocrimport',
            name='corrections',
            field=models.JSONField(blank=True, default=dict, help_text='Differences between best OCR extraction and the confirmed data.'),
        ),
        migrations.AddField(
            model_name='ocrimport',
            name='measurement_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Reference to the created Measurement in Measurements Service.', null=True),
        ),
        migrations.AddField(
            model_name='ocrimport',
            name='preprocessing_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Metadata about preprocessing methods (e.g., Deskew applied, contrast applied).'),
        ),
    ]
