# Generated by Django 5.2.14 on 2026-05-25 22:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_id', models.UUIDField(blank=True, null=True)),
                ('actor_role', models.CharField(choices=[('parent', 'Parent'), ('doctor', 'Doctor'), ('system', 'System')], max_length=50)),
                ('event_type', models.CharField(db_index=True, max_length=255)),
                ('outcome', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('denied', 'Denied')], max_length=50)),
                ('child_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('parent_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('share_id', models.UUIDField(blank=True, null=True)),
                ('resource_type', models.CharField(max_length=255)),
                ('resource_id', models.UUIDField(blank=True, null=True)),
                ('source_service', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('visible_to_parent', models.BooleanField(default=False)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
    ]
