# Generated by Django 6.0.5 on 2026-05-21 10:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parent_id', models.UUIDField(db_index=True)),
                ('child_id', models.UUIDField(db_index=True)),
                ('event_type', models.CharField(choices=[('vaccination', 'Vaccination'), ('appointment', 'Rendez-vous'), ('checkup', 'Visite de contrôle'), ('other', 'Autre')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('scheduled_date', models.DateField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planifié'), ('completed', 'Terminé'), ('cancelled', 'Annulé')], default='planned', max_length=20)),
                ('doctor_name', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('vaccine_name', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'health_events',
                'ordering': ['-scheduled_date', '-created_at'],
            },
        ),
    ]
