# Generated by Django 5.2.14 on 2026-05-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthevent',
            name='status',
            field=models.CharField(choices=[('planned', 'Planifié'), ('awaiting_confirmation', 'En attente de confirmation'), ('completed', 'Terminé'), ('cancelled', 'Annulé')], default='planned', max_length=50),
        ),
    ]
