# Generated by Django 6.0.5 on 2026-05-21 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='childshare',
            name='doctor_display_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='childshare',
            name='doctor_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
