# Generated by Django 5.2.14 on 2026-05-25 20:39

import collaboration.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration', '0002_childshare_doctor_display_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by_id', models.UUIDField()),
                ('created_by_role', models.CharField(choices=[('parent', 'Parent'), ('doctor', 'Médecin')], max_length=20)),
                ('session_type', models.CharField(choices=[('video', 'Vidéo'), ('audio', 'Audio')], default='video', max_length=10)),
                ('room_token', models.CharField(default=collaboration.models.generate_room_token, max_length=128, unique=True)),
                ('provider', models.CharField(default='jitsi', max_length=30)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Planifiée'), ('active', 'En cours'), ('completed', 'Terminée'), ('cancelled', 'Annulée')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_sessions', to='collaboration.childshare')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
