# Generated by Django 6.0.5 on 2026-05-18 14:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('child_id', models.UUIDField(db_index=True, help_text='References Child in profile_service')),
                ('parent_id', models.UUIDField(db_index=True, help_text='Set from JWT — never from request body')),
                ('measurement_id', models.UUIDField(blank=True, help_text='UUID of the measurement that triggered this alert (from measurements_service)', null=True)),
                ('alert_type', models.CharField(choices=[('growth', 'Anomalie de croissance'), ('bmi', 'Alerte IMC'), ('missing_data', 'Données manquantes'), ('follow_up', 'Suivi recommandé'), ('general', 'Information générale')], max_length=20)),
                ('severity', models.CharField(choices=[('info', 'Information'), ('warning', 'Avertissement'), ('danger', 'Danger')], default='info', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('recommendation', models.TextField(blank=True, help_text='Always non-empty for warning/danger severity. Suggests consulting a pediatrician.')),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'alerts',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('measurement_id__isnull', False)), fields=('measurement_id', 'alert_type', 'title'), name='unique_alert_per_measurement_type_title')],
            },
        ),
    ]
