# Generated by Django 5.2.14 on 2026-05-23 23:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('child_id', models.UUIDField(db_index=True, help_text='References Child in profile_service')),
                ('parent_id', models.UUIDField(db_index=True, help_text='Set from JWT — never from request body')),
                ('measurement_id', models.UUIDField(blank=True, help_text='UUID of the measurement that triggered this recommendation', null=True)),
                ('risk_score', models.IntegerField(default=0, help_text='Composite score 0–100. Hidden from parent API responses.')),
                ('risk_level', models.CharField(choices=[('low', 'Faible'), ('moderate', 'Modéré'), ('elevated', 'Élevé'), ('high', 'Risque élevé')], default='low', max_length=10)),
                ('risk_label', models.CharField(default='Faible', max_length=30)),
                ('category', models.CharField(choices=[('nutrition', 'Nutrition'), ('follow_up', 'Suivi'), ('measurement_verification', 'Vérification des mesures'), ('appointment', 'Rendez-vous'), ('doctor_consultation', 'Consultation médicale')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('why', models.TextField(help_text='Plain-language explanation of why this recommendation was generated (explainability).')),
                ('priority', models.CharField(choices=[('low', 'Basse'), ('medium', 'Moyenne'), ('high', 'Haute')], default='low', max_length=10)),
                ('factors_json', models.JSONField(default=list, help_text='Full factor breakdown array from the scoring engine at generation time.')),
                ('is_read', models.BooleanField(default=False)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('disclaimer', models.TextField(default="Ceci est un outil d'aide à la décision. Consultez un professionnel de santé.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'recommendations',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('measurement_id__isnull', False)), fields=('measurement_id', 'category', 'title'), name='unique_recommendation_per_measurement')],
            },
        ),
    ]
