# Generated by Django 5.2.14 on 2026-05-26 12:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_recommendation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parent_id', models.UUIDField(db_index=True)),
                ('child_id', models.UUIDField(db_index=True)),
                ('measurement_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('finding_code', models.CharField(max_length=80)),
                ('metric', models.CharField(max_length=40)),
                ('severity', models.CharField(max_length=20)),
                ('child_friendly_title', models.CharField(max_length=255)),
                ('parent_explanation', models.TextField()),
                ('possible_meaning', models.TextField(blank=True)),
                ('recommended_actions', models.JSONField(default=list)),
                ('evidence', models.JSONField(default=dict)),
                ('disclaimer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'clinical_findings',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('measurement_id__isnull', False)), fields=('measurement_id', 'finding_code'), name='unique_finding_per_measurement_code')],
            },
        ),
    ]
